### ISSUE TITLE
Add mention that loading tres files allows users to write any code in there

### ISSUE THREAD

**Issue by dalexeev** [GDQuest/godot-demos-2022#6]
**Never use `.res`/`.tres`/`.tscn`/etc. for untrusted sources!** These files may contain arbitrary code that will be automatically executed (`_init`).

Normal savefile:

```
[gd_resource type="Resource" load_steps=6 format=2]

[ext_resource path="res://resources/Character.gd" type="Script" id=1]
[ext_resource path="res://resources/SaveGame.gd" type="Script" id=2]
[ext_resource path="res://resources/Inventory.gd" type="Script" id=3]

[sub_resource type="Resource" id=1]
script = ExtResource( 1 )
display_name = "Godot"
run_speed = 600.0
level = 1
experience = 0
strength = 5
endurance = 5
intelligence = 5

[sub_resource type="Resource" id=2]
script = ExtResource( 3 )
items = {
"healing_gem": 3,
"sword": 1
}

[resource]
script = ExtResource( 2 )
version = 1
character = SubResource( 1 )
inventory = SubResource( 2 )
map_name = "map_1"
global_position = Vector2( 59, 410 )
```

POC of a malicious savefile:

```
[gd_resource type="Resource" load_steps=6 format=2]

[ext_resource path="res://resources/Character.gd" type="Script" id=1]
[ext_resource path="res://resources/SaveGame.gd" type="Script" id=2]
[ext_resource path="res://resources/Inventory.gd" type="Script" id=3]

[sub_resource type="Resource" id=1]
script = ExtResource( 1 )
display_name = "Godot"
run_speed = 600.0
level = 1
experience = 0
strength = 5
endurance = 5
intelligence = 5

[sub_resource type="Resource" id=2]
script = ExtResource( 3 )
items = {
"healing_gem": 3,
"sword": 1
}

[sub_resource type="GDScript" id=3]
script/source = "extends Resource

func _init():
	OS.alert(\"It's not safe. Arbitrary code can be executed.\", \"I CAN DO ANYTHING!\")
"

[sub_resource type="Resource" id=4]
script = SubResource( 3 )

[resource]
script = ExtResource( 2 )
version = 1
character = SubResource( 1 )
inventory = SubResource( 2 )
map_name = "map_1"
global_position = Vector2( 59, 410 )
__meta__ = {
"abcd": SubResource( 4 )
}
```

![](https://user-images.githubusercontent.com/47700418/176995339-924d050a-3aab-417d-b393-dcc945eaf014.png)

For example, a user might want to load another user's save. They download `save.tres` (or `save1.res`, which is human unreadable) from some website and adds it to the game's data folder. Launches the game - and unexpectedly for the user (and for inexperienced developers), all files are deleted from the user's home directory. Or vice versa: the spyware is silently downloaded and added to startup.

In the case of `.json` or `ConfigFile`, this problem does not exist (unless the developer shoots themself in the foot by doing an equivalent of `eval` on untrusted data). About `ConfigFile` I'm not sure, need to check.

`Resource` can be used for savefiles, but only if `ResourceFormatLoader` is used, i.e. if you're parsing some other format (like `.json`) than `.tres`/`.res`/`.tscn`/etc, just like you can load `.png`. However, in my opinion, this has no advantage over using `File` or `ConfigFile`.

In addition, `Resource`-based saves are more difficult to version with game updates.

I hope you make a video in which you warn about this problem.

**Comment by NathanLovato** [comment]
Your problem is that if a user downloads a save from a random source online, it could contain malicious code. Like any kind of file or program or mod they could download on the web. Even things like image files on Windows.

So I'm not sure it's a big deal. It feels to me like the user downloading files *from untrusted sources* to cheat at your game is on them.

We can add a mention of this to the demo's README though, it makes sense to be thorough and also mention that this is really about local savegames and not sharing data online.

> In addition, Resource-based saves are more difficult to version with game updates.

Not so much, if you stick to extending classes, it's not difficult to do versioning. The day you need to change the whole data structure with breaking changes, you make a new resource and convert the old save to the new format. Like how they do it in Godot.

Anyway I'm leaving this issue open for now for some more discussion. Right now I don't think it deserves a video in itself.

Though covering ConfigFile or another format with var2str/str2var could be good video topics and a good opportunity to briefly mention this.

**Comment by dalexeev** [comment]
No, I absolutely disagree with you and find your recommendation irresponsible and dangerous.

Yes, in theory any file is just data, and its security depends on how it is interpreted by other programs.

But in practice, few users expect a savefile to be dangerous, just as they don't expect it from `.txt` and `.png` files.

Programs must remain programs and data must remain data.

You are trying to shift the responsibility to users, but many of them expect or assume that the developers have taken care of their security. Whether it's right or wrong, we must consider it.

And even assuming that your option is acceptable, other options like `.json` or `File.store_var` have at least the benefit of allowing users to safely share savefiles with each other.

Forgive me if some of my words are harsh.

**Comment by dalexeev** [comment]
I want to emphasize: I don't think savefile cheating is a problem here: the user has full control over the runtime environment.

I don't even consider it a problem that with an incorrect savefile, the game can crash or work incorrectly (although this is also wrong, the game should check the validity of the savefile).

Both of these cases the user can expect. And even if they do not expect, then nothing bad will happen: the user will simply comment where they got the savefile that it is not working.

But the user has the right not to expect that the savefile may contain arbitrary code. And the consequences of this ignorance can be fatal.

**Comment by NathanLovato** [comment]
About any file can contain malicious code, really. People won't expect an image to contain a virus yet it's absolutely possible. And people don't necessarily know what's a program or that you shouldn't download files from random places or those you don't know on the web.

What do you do of mods then? Is it fine they can contain arbitrary code _because they're programs?_ Just because they're not "data files" (programs are also data), they should _expect_ (reusing your words) that there could be malicious code in there?

The number of users that'll download and run mod files without understanding the risks is much greater than downloading save files from the web. You can look at the numbers for Skyrim or the Sims, for example. Can't the consequence of ignoring that be much more fatal as the download numbers are orders of magnitude higher?

These things can run arbitrary code too and they're run by tens of millions of people.

**Comment by dalexeev** [comment]
Nathan, I have established opinions on this matter, I have no doubts, I am not asking you a question.

I informed you about the potential problem, did everything in my power and everything that I thought should be done. How you manage this information is entirely up to you. You are spreading your vision to a wide enough audience that respects you and listens to your advice. Therefore, it is up to you to decide whether to feel responsible for recommending an unsafe approach when there are safe alternatives.

I don't need to be convinced, the only important thing is that you don't convince yourself.

Anyway, thanks for your great work.

**Comment by NathanLovato** [comment]
We're having a discussion. If I didn't care, I wouldn't even answer.

Note that closing the issue is just because I've added a mention of this to the README, the discussion's not locked.

I understand that you're certain of what you think, I'm not trying to convince you of anything. I'm trying to better understand your position, hence me asking questions and not just being assertive. When I ask questions, it's not rhetorical.

Now, please also understand that it's also not a new topic for my team and me. It's not like we're just careless or stupid.

The questions I wrote above are genuine and I would appreciate your take on them.

What I got is that for you, there's a clear distinction between some files being data containers and others not, and that makes some ethical difference regarding the users. For you, it sounds like safety comes first and that we should protect regardless of how they choose to use the game (i.e. download files from non-official sources).

Please let me know if I misunderstood.

That's what raises questions like: what about mods? Is it fine that Minecraft mods, that our kids download massively, use code that could harm your computer?

Because people do that a lot without understanding the consequences or thinking about data files vs programs like you and I.

**Comment by dalexeev** [comment]
I understand that absolute security does not exist. I understand that there are other ways to break security. But I think that where it is possible to fix something, we should try to do it.

In my opinion, incompetence and low awareness is one of the main causes of many troubles around the world. Racism, homophobia, xenophobia exist in the world not because most people are evil, but because they do not understand many things and are afraid of what they do not know.

In an ideal world, all people are well versed in ethics, biology, physics, mathematics and information technology. Including that a `.txt` file is safe and `.tres` is not, and why. However, in the real world, most do not know this. For them it's just a "savefile", they don't understand if it contains data or code. And we must minimize risk where possible. Just like in other areas, no one would want to accidentally get poisoned just because they don't know chemistry well.

But even if the user is inexperienced in computers, then at best they at least understand that the program is something that can be launched with a double click, and it will do something, and all other files, including saves, do nothing on their own. Moreover, there is no application icon (window) or shared library (gear) on `.tres` files. That is, even if the user does not understand computers well, they intuitively, relying on the experience of interacting with other programs/games, assumes this. If you can share save files in one game, then you can do it in another, such logic.

As for mods.

First, there is a difference between mods and savefiles. Mods add functionality and are created by third-party developers - even less experienced users understand the risks involved (at least a larger percentage of users). Savefiles don't add functionality (and therefore don't need to be able to contain code). Save files are designed by the developers of the game, and if the user trusts the developers, then he also trusts the save files to some extent, even if they come from an untrusted source. Save files are handled by the game, and if damage is done to the user's computer due to an incorrect save file, it's the game's fault in my opinion.

Second, I'm not dismissing the fact that it would be nice to add a more secure modding system. There are relevant proposals. And in my opinion it is somehow wrong to justify the insecurity of one system by the insecurity of another.

Also, I have other reasons why I think the `Resource`-based approach is bad, but that is way beyond the scope of this discussion.

May I ask you to add a warning about potential insecurity not only in the README, but also in the description and/or pinned comment of your videos where you recommend this approach? Thanks.

**Comment by NathanLovato** [comment]
I think I got it, your point then is that we should strive to make things secure for users even if they decide to modify the product, right?

While I draw the line of responsibility at people modifying the product [from non-official sources].

> May I ask you to add a warning about potential insecurity not only in the README, but also in the description and/or pinned comment of your videos where you recommend this approach? Thanks.

Sure, I've also included a safeguard to the README, because that security issue is easy to prevent.

I'm also considering a follow-up video, but gotta see how to fit it into our busy work schedule. It's good for people to understand really how resources work.

> even less experienced users understand the risks involved

Are you sure about the assumption that people would think save files are safe but mods aren't? I'm not sure we can assume the millions of kids that played Minecraft would understand that.

I'm not even sure most Godot users understand that things like addons or tools they download could potentially do anything to their computers. I wouldn't assume it at least.

**Comment by dalexeev** [comment]
> I think I got it, your point then is that we should strive to make things secure for users even if they decide to modify the product, right?

To clarify: I don't consider savefiles to be part of the product. They are even located in a different folder (`AppData` or `.local/share`).

Everything should have reasonable limits. If something is not required, then it shouldn't be available, especially if it's not obvious. If a user or inexperienced developer sees a file

```
a=1
b=2
```

they can't be blamed for not suspecting what might be in the file

```
a=1
b=2
destroy_my_computer=true
```

and the game on launch will indeed destroy the computer. That is, if the save-load task does not require that the savefile can contain scripts, then it should not be able to contain them.

You're trying to protect developer convenience by offering what you think is a better save-load implementation. And I think that developers should be as concerned about the security of users as possible, even if it is less convenient for the developers themselves. We need to take into account the low IT competence of users, and not tell them "It's your own fault that you don't know information security well".

Also, I don't see anything wrong with being able to share savefiles and be sure they're safe. It's normal to want to play from a certain point in the game or in a certain procedurally generated world.

> Are you sure about the assumption that people would think save files are safe but mods aren't?

I would like to hope so. There is a certain percentage of people who know a little about programming, but not enough to judge the security of specific implementations. Such a user may even know what `ini`/`json` is, but know nothing about Godot, and `res`/`tres` formats. The user may well understand that mods are not safe, but not be so careful about saves.

Anyway, thanks for the discussion. I think I've changed my mind a bit too.

I think we agree that if the user shouldn't do something, then they should at least be warned about it. For example, with your approach, a developer might add a `user://saves/WARNING.txt` file.

**Comment by NathanLovato** [comment]
> You're trying to protect developer convenience by offering what you think is a better save-load implementation. 

No, that's not it at all.

As I wrote already, I draw a line as to where our responsibility lies differently from you, that's it.

**Comment by NathanLovato** [comment]
Just so you know, we're working on a video to address the issue now. We've also discussed the security with the developers for a potential solution in Godot 4.X, as currently, even ConfigFile or str2var can load resources and thus have this issue.

**Comment by dalexeev** [comment]
Yes, I noticed that `VariantParser` doesn't have the `allow_objects` parameter that binary serialization has (for example, `File.get_var`).
